### PR TITLE
Eric S's Magical Git Tagger Installation

### PR DESCRIPTION
**Pull request by gwensmu**
Add git tagger gem

### CODE REVIEW

**Comment by gwensmu** [comment]
@eschlange can you review and merge if ok? i pushed this on the wrong branch but its about git tagger.

**Comment by gwensmu** [comment]
merging this so i can finish up my TFDSO story

**Comment by eschlange** [comment]
@gwensmu sorry for the delay, your message got lost in the Slack Wall O' Text

**Comment by gwensmu** [comment]
@eschlange yr good, i figured since you'd already looked @ it i should just go ahead

**Pull request merged**
