### PR TITLE
Update Timestamps & Combine Views

### PR DESCRIPTION
**Pull request by michaelwehrley**
Update Timestamps & Create Shared Partial

* Update timestamps for likes and comments.
* Combine all feeds into a shared partial: `infinite_feed`.
* This partial is now used in host apps as well.

[#98485472]

### CODE REVIEW

**Comment by eschlange** [comment]
@michaelwehrley 
How does the profile page know to filter only the current profile's feed items?

**Comment by michaelwehrley** [comment]
It seems the feed items etc are provided when we bootstrap angular.
**ThinkFeelDoSo**:
/profile_pages/show: https://github.com/cbitstech/social_networking/blob/master/app/views/social_networking/profile_pages/show.html.erb#L239
/homes/show: https://github.com/cbitstech/social_networking/blob/master/app/views/social_networking/homes/show.html.erb#L150
**SunnySide**
/profile_pages/show: https://github.com/cbitstech/sunnyside/blob/master/app/views/social_networking/profile_pages/show.html.erb#L211
/homes/show: https://github.com/cbitstech/sunnyside/blob/master/app/views/social_networking/homes/show.html.erb#L201

**Comment by eschlange** [comment]
@michaelwehrley But now, the feed items are being loaded via Ajax with the feed service. So only the first feed items loaded would be filtered.

**Comment by michaelwehrley** [comment]
I will get back to you on that - good point!

**Comment by eschlange** [comment]
Good work!

**Pull request merged**
