### PR TITLE
Add unit specs for social reports

### PR DESCRIPTION
**Pull request by gwensmu**
[#90041694]

### CODE REVIEW

**Comment by ericcf** [comment]
I'd like to see a test for the data itself for each report, similar to https://github.com/cbitstech/think_feel_do_engine/blob/master/spec/models/think_feel_do_engine/reports/site_session_spec.rb

**Comment by gwensmu** [comment]
roger

**Comment by gwensmu** [comment]
@ericcf updated

**Comment by ericcf** [comment]
:pouting_cat:

**Pull request merged**
